Develop RQ_VANNER_1.0
STRCapstone/StyleTransfer_Capstone pull request #25
Opened 2024-05-05 09:44 UTC by youngeunyoon

### 구현 내용
__init__.py, index.html 편집
vanner.html, vanner_style.css 추가

#### __init__.py
기본 flask 코드 추가

#### index.html
기본 html 구조 및 배너 include 코드

#### vanner.html
배너 내용 코드

#### vanner_style.css
배너 관련 style 코드

### 실행 예시
![image](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/94973258/94a33c4d-d149-4edb-a1ee-4eabafe7edfc)

2024-05-05 10:25 UTC, JuYeolYang requested changes
index.html 부분만 수정하면 될 것 같습니다

2024-05-05 10:25 UTC, JuYeolYang commented on web/app/templates/index.html
> +        <script src="{{url_for('static', filename='js/vanner_include.js')}}"></script>
vanner_include.js파일을 사용하지 않기 때문에 이 코드는 삭제하는게 좋을 것 같네

2024-05-05 18:46 UTC, JuYeolYang approved these changes
good

2024-05-06 16:59 UTC, segangoh commented
문제 없어보이는데 확인 한번더 해보겠습니다

2024-05-06 17:03 UTC, segangoh reviewed
확인했습니다

2024-05-06 17:03 UTC, segangoh approved these changes

2024-05-06 17:07 UTC, JuYeolYang approved these changes

2024-05-06 17:29 UTC, merged