Develop ST_PROCESS 1.0
STRCapstone/StyleTransfer_Capstone pull request #27
Opened 2024-05-10 09:24 UTC by segangoh

### 구현 내용
transfer.html 추가
transfer_style.css 추가
transfer.js 추가
image file 업로드

transfer.html
process바 코드 작성

transfer_style.css
transfer.html의 style 코드

transfer.js
transfer.html의 js 코드

image files
transfer.html에 들어갈 vector_next_triangle.png업로드

**실행 예시**
![image](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/54662446/b91e85d5-0300-4142-80c3-02b91501acee)
시작 화면

![image](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/54662446/1397b88b-34d9-46ff-879e-e2b02b3b756f)
next버튼 2번 눌렀을때

![image](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/54662446/707b516b-54b9-4c45-8b3f-91454a819227)
사진 업로드 단계를 눌러 다시 돌아갔을때

2024-05-10 09:35 UTC, JuYeolYang commented on web/app/static/js/transfer.js
> +function step1Back(){
javascript에도 class가 있습니다. class를 만들어서 작성해보세요

2024-05-10 09:37 UTC, JuYeolYang commented on web/app/templates/transfer/transfer.html
> +                <span class = "step active" onclick="step1Back();">���ε� ���� ����</span>
getElementByID로 해당 ID 블럭을 불러올 수 있고 불러온 블럭의 value값을 알아낼 수 있습니다. javascript랑 연동해서 작성해보세요

2024-05-10 09:38 UTC, JuYeolYang requested changes
전체적인 개선점 코드에 추가해 놓았습니다. 참고해서 재작성 후 pr 보내주세요. 질문은 개인 메신저로 받겠습니다

2024-05-10 09:56 UTC, segangoh commented on web/app/static/js/transfer.js
> +function step1Back(){
어떤 부분의 class를 말하는건지 코드 부분을 다시 찝어주기바랍니다 functioin stepBack 파트들을 얘기하는 걸까요 currentStep에 관한 내용일까요?

2024-05-10 09:59 UTC, segangoh commented on web/app/templates/transfer/transfer.html
> +                <span class = "step active" onclick="step1Back();">���ε� ���� ����</span>
블럭 value 값을 알아도 currentStep 변수로 처리하는데 필요한 inex값을 알아올 수 없습니다. 블럭 ID를 통해 currentStep을 바꾸는게 onclick보다 어떤 이점이 있을까요?

2024-05-10 10:13 UTC, JuYeolYang commented on web/app/templates/transfer/transfer.html
> +                <span class = "step active" onclick="step1Back();">���ε� ���� ����</span>
js에서 단 코멘트와 위의 코멘트와 연관되어 있기 때문에 한번에 질문에 답변하겠습니다. step1Back, step2Back... 이렇게 하는 건 같은 코드가 반복적으로 호출되기 때문에 좋은 코드라고 볼수 없습니다. class를 생성해서 한번에 처리할 수 있고 필요한 변수(여기선는 currentStep 변수라고 볼 수 있겠네요)를 저장할 수 있습니다. 각 객체를 만들어서 관리하는 편이 더 좋은 방향이라고 생각합니다. 
그리고 value값을 알면 index를 모른다고 했는데 value를 index처럼 처리하면 되지 않을까요. 저는 충분히 구현가능하다고 봅니다.

지금 확인했는데 왜 pr 제목이 ST_PROCESS 1.0인가요? 이슈 이름 그대로 작성해주시기 바랍니다. 그리고 issue ST_PROCESS 가보시면 요구사항이 있는데 next버튼을 생성해서 전 작업으로 돌아가지 않습니다. 요구사항대로 코드 구현해주시기 바랍니다.

2024-05-10 12:57 UTC, youngeunyoon requested changes
파일 인코딩 UTF-8로 변경 부탁드립니다.

2024-05-10 12:57 UTC, youngeunyoon commented on web/app/templates/transfer/transfer.html
> +        <link rel="stylesheet" href="../../static/css/transfer_style.css">
develop에 올릴 때는 flask 코드로 변경 후 업로드 하는 것이 좋을 것 같습니다.

2024-05-13 05:39 UTC, segangoh commented on web/app/templates/transfer/transfer.html
> +                <span class = "step active" onclick="step1Back();">���ε� ���� ����</span>
클래스 생성 대신 같은 코드 반복 호출 줄이기 위해서 onclick시 매개변수를 주는 것으로 해결했습니다. 확인 부탁드립니다.

2024-05-13 05:39 UTC, segangoh commented on web/app/templates/transfer/transfer.html
> +        <link rel="stylesheet" href="../../static/css/transfer_style.css">
변경했습니다.

2024-05-13 05:39 UTC, segangoh commented on web/app/templates/transfer/transfer.html
> +        <script src="../../static/js/transfer.js">
변경했습니다.

2024-05-13 05:44 UTC, segangoh commented on web/app/static/js/transfer.js
> +function step1Back(){
매개변수를 사용하여 하나의 함수로 수정했습니다 확인 부탁드립니다.

2024-05-13 05:47 UTC, segangoh commented on web/app/templates/transfer/transfer.html
> +                <span class = "step active" onclick="step1Back();">���ε� ���� ����</span>
next 버튼 제거 했습니다. 확인 부탁드립니다.

2024-05-13 09:35 UTC, youngeunyoon approved these changes

2024-05-14 00:03 UTC, JuYeolYang approved these changes

2024-05-14 00:03 UTC, merged