Develop RQ_SBOX
STRCapstone/StyleTransfer_Capstone pull request #51
Opened 2024-05-28 15:57 UTC by youngeunyoon

### 구현 내용
mypage에서 사진 클릭 시 savebox image popup
다운로드, 삭제 기능

### 실행 예시
![image](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/94973258/414ed587-0ba2-4639-a4b9-0a163b5816e2)

2024-05-28 16:06 UTC, JuYeolYang requested changes

2024-05-28 16:06 UTC, JuYeolYang commented on web/app/static/js/mypage.js
> +    await fetch("/mypage/deletesavebox", {
flask에서 리턴되는 값이 있는데 그 부분에 대한 후처리가 없습니다.

2024-05-28 16:06 UTC, JuYeolYang commented on web/app/static/js/mypage.js
> +    location.href = "/mypage";
이부분을 flask에서 response값을 받아와서 정상 작동하였다면 mypage로 리다이렉션하는 코드로 바꿔주세요

2024-05-28 16:06 UTC, JuYeolYang commented on web/app/templates/member/mypage.html
> +                <a id="savebox_download_button" href = "/{{user_data[0]}}/" download><img id="savebox_download" src="../../static/images/mypage/vector_download.png"></a>
src부분이 상대경로로 작성되어있는데 url_for('static', ...)을 이용하면 더 깔끔하게 표현 가능할 것 같습니다. 이 부분은 codecleanup 브랜치에서 해결해주세요

2024-05-28 16:09 UTC, JuYeolYang commented on web/app/static/js/mypage.js
> +    location.href = "/mypage";
이 부분은 transfer.js에 이미 구현되어 있으므로 참고해서 작성해보세요

2024-05-28 16:21 UTC, youngeunyoon commented on web/app/static/js/mypage.js
> +    await fetch("/mypage/deletesavebox", {
수정했습니다. 확인 부탁드립니다.

2024-05-28 16:21 UTC, youngeunyoon commented on web/app/static/js/mypage.js
> +    location.href = "/mypage";
수정했습니다. 확인 부탁드립니다.

2024-05-28 16:24 UTC, youngeunyoon commented on web/app/templates/member/mypage.html
> +                <a id="savebox_download_button" href = "/{{user_data[0]}}/" download><img id="savebox_download" src="../../static/images/mypage/vector_download.png"></a>
이 부분과 비슷하게 현재 웹페이지에 기본적으로 삽입되는 아이콘 이미지의 경우 web/app/static/images에 위치하고, 모두 상대경로 기반으로 작성되어 있습니다. CODECLEANUP branch에서 모든 아이콘 이미지의 경로를 수정해야할까요?

2024-05-28 16:27 UTC, JuYeolYang commented on web/app/templates/member/mypage.html
> +                <a id="savebox_download_button" href = "/{{user_data[0]}}/" download><img id="savebox_download" src="../../static/images/mypage/vector_download.png"></a>
네. 그렇게 하는게 코드가 더 간결하고 직관적으로 보일 수 있을 것 같습니다.

2024-05-28 16:28 UTC, JuYeolYang approved these changes
나중에 이미지 경로 관련된 것은 모두 codecleanup에서 해결하도록합시다. 고생하셨어요

2024-05-28 16:28 UTC, youngeunyoon commented on web/app/templates/member/mypage.html
> +                <a id="savebox_download_button" href = "/{{user_data[0]}}/" download><img id="savebox_download" src="../../static/images/mypage/vector_download.png"></a>
넵 알겠습니다. 추후 반영하여 수정하도록 하겠습니다.

2024-05-29 03:48 UTC, segangoh approved these changes
수고하셨습니다

2024-05-29 03:49 UTC, merged